# Generated by Django 4.2.6 on 2023-10-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='title',
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
    ]
