# Generated by Django 4.2.6 on 2023-12-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stream',
            new_name='IPCamera',
        ),
    ]
