# Generated by Django 4.2.6 on 2023-12-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_stream_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rtsp_url', models.CharField(max_length=200)),
            ],
        ),
    ]
