# Generated by Django 4.2.6 on 2023-12-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_streamview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamView',
        ),
    ]
