# Generated by Django 4.2.6 on 2023-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_delete_streamview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
